Added the KeyCloackUsersList
gh05tdog/DAPM_Master_Thesis_Group_D pull request #119
Opened 2024-10-28 20:14 UTC by gh05tdog

If a user has the view-users role in Keycloack a list in the sidebar will spawn containng the KeycloakUsers and userid

2024-10-29 08:58 UTC, RasmusUK requested changes
If the user is required to have the ` view-users` role then I suggest that you make sure that the roles 'PipelineManager` etc. have that as a composite such that they can get the information which will be required for them to be able to see users and add them to the respective entity. Just like how the role manager incorporates all the rest of the roles. So please add that to the realm.json.

2024-10-29 11:02 UTC, gh05tdog commented
@RasmusUK The view-users have now been added to the roles

2024-10-29 14:25 UTC, gh05tdog reviewed
It should have been fixed now

2024-10-30 07:15 UTC, RasmusUK approved these changes

2024-11-01 12:12 UTC, merged